/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000f22",
        "inverse-on-surface": "#eef1f4",
        "on-secondary-fixed": "#3c0700",
        "on-primary-fixed": "#001c37",
        "on-surface": "#181c1e",
        "secondary-container": "#fe5e37",
        "on-secondary-fixed-variant": "#8a1c00",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#bdc7dc",
        "background": "#f7fafd",
        "surface-container-low": "#f1f4f7",
        "on-tertiary-fixed-variant": "#3d4759",
        "on-tertiary": "#ffffff",
        "tertiary": "#050e1d",
        "secondary-fixed": "#ffdad2",
        "on-tertiary-container": "#818b9f",
        "on-surface-variant": "#43474d",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b0c8eb",
        "surface-variant": "#e0e3e6",
        "secondary-fixed-dim": "#ffb4a2",
        "primary-fixed": "#d2e4ff",
        "surface-dim": "#d7dadd",
        "surface-container-highest": "#e0e3e6",
        "tertiary-container": "#1a2434",
        "secondary": "#b32a03",
        "tertiary-fixed": "#d9e3f9",
        "on-secondary-container": "#5a0f00",
        "on-background": "#181c1e",
        "surface": "#f7fafd",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c6ce",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#314865",
        "outline": "#74777e",
        "on-tertiary-fixed": "#121c2b",
        "on-primary-container": "#768dad",
        "surface-container": "#ebeef1",
        "inverse-primary": "#b0c8eb",
        "primary-container": "#0a2540",
        "surface-bright": "#f7fafd",
        "surface-tint": "#49607e",
        "surface-container-high": "#e5e8eb",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
