/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "var(--color-ink)",
        "inverse-on-surface": "var(--color-paper)",
        "on-secondary-fixed": "var(--color-ink)",
        "on-primary-fixed": "var(--color-ink)",
        "on-surface": "var(--color-ink)",
        "secondary-container": "var(--color-accent)",
        "on-secondary-fixed-variant": "var(--color-accent-hover)",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "var(--color-ink-variant)",
        "background": "var(--color-paper)",
        "surface-container-low": "var(--color-paper-low)",
        "on-tertiary-fixed-variant": "var(--color-ink-variant)",
        "on-tertiary": "var(--color-paper)",
        "tertiary": "var(--color-ink)",
        "secondary-fixed": "var(--color-paper-low)",
        "on-tertiary-container": "var(--color-ink-variant)",
        "on-surface-variant": "var(--color-ink-variant)",
        "surface-container-lowest": "var(--color-paper-lowest)",
        "on-secondary": "var(--color-paper)",
        "primary-fixed-dim": "var(--color-ink-variant)",
        "surface-variant": "var(--color-paper-low)",
        "secondary-fixed-dim": "var(--color-accent)",
        "primary-fixed": "var(--color-paper-lowest)",
        "surface-dim": "var(--color-paper-low)",
        "surface-container-highest": "var(--color-paper-high)",
        "tertiary-container": "var(--color-paper-lowest)",
        "secondary": "var(--color-accent-hover)",
        "tertiary-fixed": "var(--color-paper)",
        "on-secondary-container": "var(--color-ink)",
        "on-background": "var(--color-ink)",
        "surface": "var(--color-paper)",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "outline-variant": "var(--color-border)",
        "on-primary": "var(--color-paper)",
        "on-primary-fixed-variant": "var(--color-ink-variant)",
        "outline": "var(--color-ink-variant)",
        "on-tertiary-fixed": "var(--color-ink)",
        "on-primary-container": "var(--color-ink-variant)",
        "surface-container": "var(--color-paper-low)",
        "inverse-primary": "var(--color-accent)",
        "primary-container": "var(--color-paper-lowest)",
        "surface-bright": "var(--color-paper-lowest)",
        "surface-tint": "var(--color-accent)",
        "surface-container-high": "var(--color-paper-high)",
        "inverse-surface": "var(--color-ink)",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "display-serif": ["'Cormorant Garamond'", "serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
